version: "3.8"

services:
  app-prod:
    image: ${APP_IMAGE}:latest
    restart: always
    ports:
      - 5000:5000
    env_file:
      - .env
    networks:
      - absensi
  
  app-staging:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5001:5000
    env_file:
      - .env
    networks:
      - absensi

  app-dev:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5002:5000
    env_file:
      - .env
    networks:
      - absensi

  database:
    container_name: database
    build:
      context: ./postgres
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - absensi

networks:
  absensi:

volumes:
  pgdata: